[package]
name = "tap"
version = "0.1.0"
edition = "2024"
authors = ["Charlie Karafotias <cnkara2023@gmail.com>"]
repository = "https://github.com/CharlieKarafotias/tap"
description = "Quickly access links associated with a parent entity"

[dependencies]

